"""make_user_external_id_not_null

Revision ID: 98276fd36c76
Revises: 448015e66968
Create Date: 2026-03-01 12:39:03.252055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98276fd36c76'
down_revision: Union[str, Sequence[str], None] = '448015e66968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill any existing rows that have NULL external_id
    op.execute(
        "UPDATE \"user\" SET external_id = 'system:' || id::text "
        "WHERE external_id IS NULL OR external_id = ''"
    )
    op.alter_column('user', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
