"""definitive_21_table_schema

Revision ID: 68be94d35f2c
Revises: 0001
Create Date: 2026-02-25 11:30:50.417689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68be94d35f2c'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.Text(), nullable=True),
    sa.Column('interswitch_merchant_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('business_is_active_idx', 'business', ['is_active'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('business_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('onboarding_step', sa.Text(), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('onboarding_completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('monthly_txn_volume_range', sa.String(length=50), nullable=True),
    sa.Column('avg_monthly_payouts_range', sa.String(length=50), nullable=True),
    sa.Column('primary_bank', sa.String(length=100), nullable=True),
    sa.Column('primary_use_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_appetite', sa.Text(), nullable=True),
    sa.Column('default_risk_tolerance', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.3500'), nullable=False),
    sa.Column('default_budget_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("onboarding_step IN ('not_started', 'business_profile', 'financial_setup', 'team_invite', 'complete')", name='business_config_onboarding_step_check'),
    sa.CheckConstraint("risk_appetite IN ('conservative', 'moderate', 'aggressive')", name='business_config_risk_appetite_check'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('business_member',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), server_default=sa.text("'analyst'"), nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'approver', 'analyst')", name='business_member_role_check'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'user_id', name='business_member_business_user_unique')
    )
    op.create_index('business_member_business_id_idx', 'business_member', ['business_id'], unique=False)
    op.create_index('business_member_user_id_idx', 'business_member', ['user_id'], unique=False)
    op.create_table('invitation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('accepted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('approver', 'analyst')", name='invitation_role_check'),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'expired', 'revoked')", name='invitation_status_check'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('invitation_business_id_idx', 'invitation', ['business_id'], unique=False)
    op.create_index('invitation_email_idx', 'invitation', ['email'], unique=False)
    op.create_index('invitation_expires_at_idx', 'invitation', ['expires_at'], unique=False)
    op.create_table('forecast_result',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('balance_today', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_payout_batch', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('projected_balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('feasibility', sa.Text(), nullable=False),
    sa.Column('stress_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inflow_7d_projected', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('outflow_7d_projected', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_7d_projected', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('daily_projections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("feasibility IN ('safe', 'caution', 'block')", name='forecast_result_feasibility_check'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('forecast_result_business_id_idx', 'forecast_result', ['business_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('send_attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_attempt_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'in_app', 'whatsapp')", name='notification_outbox_channel_check'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('notification_outbox_business_id_idx', 'notification_outbox', ['business_id'], unique=False)
    op.create_index('notification_outbox_scheduled_for_idx', 'notification_outbox', ['scheduled_for'], unique=False)
    op.create_index('notification_outbox_unsent_idx', 'notification_outbox', ['is_sent'], unique=False, postgresql_where=sa.text('is_sent = false'))
    op.create_index('notification_outbox_user_id_idx', 'notification_outbox', ['user_id'], unique=False)
    op.create_table('reconciled_transaction',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('interswitch_ref', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'NGN'"), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('transaction_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('counterparty_bank', sa.String(length=100), nullable=True),
    sa.Column('has_anomaly', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('anomaly_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('CARD', 'TRANSFER', 'USSD', 'QR')", name='reconciled_transaction_channel_check'),
    sa.CheckConstraint("direction IN ('inflow', 'outflow')", name='reconciled_transaction_direction_check'),
    sa.CheckConstraint("status IN ('SUCCESS', 'PENDING', 'FAILED', 'REVERSED')", name='reconciled_transaction_status_check'),
    sa.CheckConstraint('amount >= 0', name='reconciled_transaction_amount_check'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'interswitch_ref', name='reconciled_transaction_run_ref_unique')
    )
    op.create_index('reconciled_transaction_business_id_idx', 'reconciled_transaction', ['business_id'], unique=False)
    op.create_index('reconciled_transaction_has_anomaly_idx', 'reconciled_transaction', ['has_anomaly'], unique=False)
    op.create_index('reconciled_transaction_interswitch_ref_idx', 'reconciled_transaction', ['interswitch_ref'], unique=False)
    op.create_index('reconciled_transaction_run_id_idx', 'reconciled_transaction', ['run_id'], unique=False)
    op.create_index('reconciled_transaction_status_idx', 'reconciled_transaction', ['status'], unique=False)
    op.create_index('reconciled_transaction_txn_timestamp_idx', 'reconciled_transaction', [sa.literal_column('transaction_timestamp DESC')], unique=False)
    op.create_table('run_step',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Text(), nullable=False),
    sa.Column('step_order', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('progress_pct', sa.SmallInteger(), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent_type IN ('planner', 'reconciliation', 'risk', 'forecast', 'execution', 'audit')", name='run_step_agent_type_check'),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'skipped')", name='run_step_status_check'),
    sa.CheckConstraint('step_order >= 0', name='run_step_step_order_check'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_order', name='run_step_run_id_step_order_unique')
    )
    op.create_index('run_step_run_id_idx', 'run_step', ['run_id'], unique=False)
    op.create_index('run_step_run_id_step_order_idx', 'run_step', ['run_id', 'step_order'], unique=False)
    op.create_table('api_call_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('http_method', sa.String(length=8), nullable=False),
    sa.Column('http_status_code', sa.SmallInteger(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('request_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('called_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent_type IN ('planner', 'reconciliation', 'risk', 'forecast', 'execution', 'audit')", name='api_call_log_agent_type_check'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['run_step.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('api_call_log_called_at_idx', 'api_call_log', ['called_at'], unique=False, postgresql_using='brin')
    op.create_index('api_call_log_run_id_idx', 'api_call_log', ['run_id'], unique=False)
    op.create_index('api_call_log_step_id_idx', 'api_call_log', ['step_id'], unique=False)
    op.create_table('run_event',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sequence_num', sa.Integer(), nullable=False),
    sa.Column('emitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['run_step.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('run_event_run_id_idx', 'run_event', ['run_id'], unique=False)
    op.create_index('run_event_run_id_sequence_num_idx', 'run_event', ['run_id', 'sequence_num'], unique=False)
    op.create_table('transaction_anomaly',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('txn_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_value', sa.String(length=255), nullable=True),
    sa.Column('expected_range', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high')", name='transaction_anomaly_severity_check'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['txn_id'], ['reconciled_transaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('transaction_anomaly_run_id_idx', 'transaction_anomaly', ['run_id'], unique=False)
    op.create_index('transaction_anomaly_txn_id_idx', 'transaction_anomaly', ['txn_id'], unique=False)
    op.create_index('transaction_anomaly_type_idx', 'transaction_anomaly', ['anomaly_type'], unique=False)
    op.create_table('approval_override',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('overridden_by', sa.UUID(), nullable=False),
    sa.Column('original_decision', sa.Text(), nullable=False),
    sa.Column('original_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('new_decision', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('overridden_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("new_decision IN ('allow', 'review', 'block')", name='approval_override_new_decision_check'),
    sa.CheckConstraint("original_decision IN ('allow', 'review', 'block')", name='approval_override_original_decision_check'),
    sa.ForeignKeyConstraint(['candidate_id'], ['payout_candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overridden_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('approval_override_candidate_id_idx', 'approval_override', ['candidate_id'], unique=False)
    op.create_index('approval_override_overridden_by_idx', 'approval_override', ['overridden_by'], unique=False)
    op.create_index('approval_override_run_id_idx', 'approval_override', ['run_id'], unique=False)
    op.create_table('customer_lookup_result',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('institution_code', sa.String(length=10), nullable=False),
    sa.Column('name_returned', sa.String(length=255), nullable=True),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('http_status_code', sa.SmallInteger(), nullable=False),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('called_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['payout_candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('customer_lookup_result_candidate_id_idx', 'customer_lookup_result', ['candidate_id'], unique=False)
    op.create_index('customer_lookup_result_run_id_idx', 'customer_lookup_result', ['run_id'], unique=False)
    op.create_table('payout_execution',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('submission_type', sa.Text(), nullable=False),
    sa.Column('interswitch_reference', sa.String(length=128), nullable=True),
    sa.Column('http_status_code', sa.SmallInteger(), nullable=False),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('execution_status', sa.Text(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('called_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("execution_status IN ('pending', 'success', 'failed', 'requires_followup')", name='payout_execution_status_check'),
    sa.CheckConstraint("submission_type IN ('submission', 'status_poll')", name='payout_execution_submission_type_check'),
    sa.ForeignKeyConstraint(['candidate_id'], ['payout_candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('payout_execution_called_at_idx', 'payout_execution', ['called_at'], unique=False, postgresql_using='brin')
    op.create_index('payout_execution_candidate_id_idx', 'payout_execution', ['candidate_id'], unique=False)
    op.create_index('payout_execution_interswitch_ref_idx', 'payout_execution', ['interswitch_reference'], unique=False, postgresql_where=sa.text('interswitch_reference IS NOT NULL'))
    op.create_index('payout_execution_run_id_idx', 'payout_execution', ['run_id'], unique=False)
    op.create_table('risk_score_feature',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('historical_frequency', sa.Integer(), nullable=True),
    sa.Column('amount_deviation_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_historical_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('duplicate_similarity_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('lookup_mismatch_flag', sa.Boolean(), nullable=True),
    sa.Column('account_anomaly_count', sa.SmallInteger(), nullable=True),
    sa.Column('account_age_days', sa.Integer(), nullable=True),
    sa.Column('days_since_last_payout', sa.Integer(), nullable=True),
    sa.Column('amount_vs_budget_cap_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['payout_candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_index('risk_score_feature_run_id_idx', 'risk_score_feature', ['run_id'], unique=False)

    # --- Data migration: operator → user, create default business ---
    # 1. Drop old FKs BEFORE dropping old tables
    op.drop_constraint(op.f('agent_run_operator_id_fkey'), 'agent_run', type_='foreignkey')
    op.drop_constraint(op.f('payout_candidate_approved_by_fkey'), 'payout_candidate', type_='foreignkey')
    op.drop_constraint(op.f('audit_log_step_id_fkey'), 'audit_log', type_='foreignkey')

    # 2. Migrate operator rows → user table (preserve UUIDs)
    op.execute("""
        INSERT INTO "user" (id, external_id, email, display_name, is_active, created_at, updated_at)
        SELECT id, external_id, email, display_name, is_active, created_at, updated_at
        FROM operator
        ON CONFLICT DO NOTHING
    """)

    # 3. Create a default business for existing data
    op.execute("""
        INSERT INTO business (id, business_name, is_active)
        VALUES ('00000000-0000-0000-0000-000000000001', 'Default Business (migrated)', true)
        ON CONFLICT DO NOTHING
    """)

    # 4. Drop old indexes and tables
    op.drop_index(op.f('plan_step_run_id_idx'), table_name='plan_step')
    op.drop_table('plan_step')
    op.drop_index(op.f('transaction_run_id_idx'), table_name='transaction')
    op.drop_index(op.f('transaction_run_id_status_idx'), table_name='transaction')
    op.drop_index(op.f('transaction_timestamp_idx'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('operator')

    # 5. Add new columns as NULLABLE first, then backfill, then set NOT NULL
    op.add_column('agent_run', sa.Column('business_id', sa.UUID(), nullable=True))
    op.add_column('agent_run', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('agent_run', sa.Column('date_from', sa.Date(), nullable=True))
    op.add_column('agent_run', sa.Column('date_to', sa.Date(), nullable=True))
    op.add_column('agent_run', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('agent_run', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('agent_run', sa.Column('cancelled_by', sa.UUID(), nullable=True))
    op.add_column('agent_run', sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('agent_run', 'risk_tolerance',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text('0.35'))
    op.alter_column('agent_run', 'budget_cap',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)

    # 6. Backfill existing agent_run rows: operator_id → created_by, default business
    op.execute("""
        UPDATE agent_run
        SET business_id = '00000000-0000-0000-0000-000000000001',
            created_by = COALESCE(operator_id, '00000000-0000-0000-0000-000000000001')
        WHERE business_id IS NULL
    """)
    op.alter_column('agent_run', 'business_id', nullable=False)
    op.alter_column('agent_run', 'created_by', nullable=False)

    op.drop_index(op.f('agent_run_operator_id_created_at_idx'), table_name='agent_run')
    op.drop_index(op.f('agent_run_operator_id_idx'), table_name='agent_run')
    op.create_index('agent_run_business_id_created_at_idx', 'agent_run', ['business_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('agent_run_business_id_idx', 'agent_run', ['business_id'], unique=False)
    op.create_index('agent_run_created_by_idx', 'agent_run', ['created_by'], unique=False)
    op.create_foreign_key('agent_run_cancelled_by_fkey', 'agent_run', 'user', ['cancelled_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('agent_run_business_id_fkey', 'agent_run', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('agent_run_created_by_fkey', 'agent_run', 'user', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('agent_run_approved_by_fkey', 'agent_run', 'user', ['approved_by'], ['id'], ondelete='SET NULL')
    op.drop_column('agent_run', 'operator_id')

    # audit_log FK already dropped above; just re-create pointing to run_step
    op.create_foreign_key('audit_log_step_id_fkey', 'audit_log', 'run_step', ['step_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_log', 'response_time_ms')
    op.drop_column('audit_log', 'request_hash')
    op.drop_column('audit_log', 'response_status')
    op.drop_column('audit_log', 'api_endpoint')
    op.add_column('institution', sa.Column('short_name', sa.String(length=50), nullable=True))
    op.add_column('institution', sa.Column('institution_type', sa.Text(), nullable=True))
    op.add_column('institution', sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('payout_batch', sa.Column('business_id', sa.UUID(), nullable=True))
    op.alter_column('payout_batch', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    # Backfill payout_batch.business_id from parent agent_run
    op.execute("""
        UPDATE payout_batch pb
        SET business_id = ar.business_id
        FROM agent_run ar
        WHERE pb.run_id = ar.id AND pb.business_id IS NULL
    """)
    op.alter_column('payout_batch', 'business_id', nullable=False)
    op.create_index('payout_batch_business_id_idx', 'payout_batch', ['business_id'], unique=False)
    op.create_foreign_key('payout_batch_business_id_fkey', 'payout_batch', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('payout_candidate', sa.Column('business_id', sa.UUID(), nullable=True))
    op.alter_column('payout_candidate', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('payout_candidate', 'risk_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('payout_candidate', 'lookup_match_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    # Backfill payout_candidate.business_id from parent agent_run
    op.execute("""
        UPDATE payout_candidate pc
        SET business_id = ar.business_id
        FROM agent_run ar
        WHERE pc.run_id = ar.id AND pc.business_id IS NULL
    """)
    op.alter_column('payout_candidate', 'business_id', nullable=False)
    op.create_index('payout_candidate_business_id_idx', 'payout_candidate', ['business_id'], unique=False)
    # payout_candidate FK already dropped above; just re-create pointing to user + business
    op.create_foreign_key('payout_candidate_business_id_fkey', 'payout_candidate', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('payout_candidate_approved_by_fkey', 'payout_candidate', 'user', ['approved_by'], ['id'], ondelete='SET NULL')

    # 7. Create set_updated_at trigger for new mutable tables
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    for tbl in [
        'user', 'business', 'business_config', 'business_member', 'invitation',
        'reconciled_transaction', 'run_step', 'forecast_result',
        'notification_outbox',
    ]:
        op.execute(f"""
            CREATE TRIGGER trg_{tbl}_updated_at
            BEFORE UPDATE ON \"{tbl}\"
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """)

    # 8. Add institution_type_check constraint
    op.create_check_constraint(
        'institution_type_check', 'institution',
        "institution_type IN ('bank', 'mobile_money', 'microfinance', 'other')"
    )

    # 9. Add missing FK-supporting indexes
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS agent_run_approved_by_idx ON agent_run (approved_by)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS agent_run_cancelled_by_idx ON agent_run (cancelled_by)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS invitation_invited_by_idx ON invitation (invited_by)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS run_event_step_id_idx ON run_event (step_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS notification_outbox_run_id_idx ON notification_outbox (run_id)'))

    # 10. Add missing audit_log indexes (not in baseline)
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS audit_log_run_id_idx ON audit_log (run_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS audit_log_step_id_idx ON audit_log (step_id)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS audit_log_run_id_created_at_idx ON audit_log (run_id, created_at DESC)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS audit_log_created_at_brin_idx ON audit_log USING brin (created_at)'))
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS audit_log_detail_gin_idx ON audit_log USING gin (detail)'))

    # 11. Add missing payout_candidate GIN index
    op.execute(sa.text('CREATE INDEX IF NOT EXISTS payout_candidate_risk_reasons_idx ON payout_candidate USING gin (risk_reasons)'))

    # 12. Drop redundant run_step index (unique constraint already creates one)
    op.drop_index('run_step_run_id_step_order_idx', table_name='run_step')

    # 13. Fix invitation.invited_by and approval_override.overridden_by to be nullable
    #     (required for SET NULL ondelete to work)
    op.alter_column('invitation', 'invited_by', nullable=True)
    op.alter_column('approval_override', 'overridden_by', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes on persistent tables (added in upgrade steps 9-12)
    op.drop_index('payout_candidate_risk_reasons_idx', table_name='payout_candidate', postgresql_using='gin')
    op.drop_index('audit_log_detail_gin_idx', table_name='audit_log', postgresql_using='gin')
    op.drop_index('audit_log_created_at_brin_idx', table_name='audit_log', postgresql_using='brin')
    op.drop_index('audit_log_run_id_created_at_idx', table_name='audit_log')
    op.drop_index('audit_log_step_id_idx', table_name='audit_log')
    op.drop_index('audit_log_run_id_idx', table_name='audit_log')
    op.drop_index('agent_run_approved_by_idx', table_name='agent_run')
    op.drop_index('agent_run_cancelled_by_idx', table_name='agent_run')

    op.drop_constraint('payout_candidate_business_id_fkey', 'payout_candidate', type_='foreignkey')
    op.drop_constraint('payout_candidate_approved_by_fkey', 'payout_candidate', type_='foreignkey')
    # NOTE: payout_candidate→operator FK deferred until after operator table is re-created
    op.drop_index('payout_candidate_business_id_idx', table_name='payout_candidate')
    op.alter_column('payout_candidate', 'lookup_match_score',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('payout_candidate', 'risk_score',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('payout_candidate', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.drop_column('payout_candidate', 'business_id')
    op.drop_constraint('payout_batch_business_id_fkey', 'payout_batch', type_='foreignkey')
    op.drop_index('payout_batch_business_id_idx', table_name='payout_batch')
    op.alter_column('payout_batch', 'total_amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.drop_column('payout_batch', 'business_id')
    op.drop_column('institution', 'raw_response')
    op.drop_column('institution', 'institution_type')
    op.drop_column('institution', 'short_name')
    op.add_column('audit_log', sa.Column('api_endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('audit_log', sa.Column('response_status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('audit_log', sa.Column('request_hash', sa.CHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('audit_log', sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('audit_log_step_id_fkey', 'audit_log', type_='foreignkey')
    # NOTE: audit_log→plan_step FK deferred until after plan_step table is re-created
    op.add_column('agent_run', sa.Column('operator_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('agent_run_cancelled_by_fkey', 'agent_run', type_='foreignkey')
    op.drop_constraint('agent_run_business_id_fkey', 'agent_run', type_='foreignkey')
    op.drop_constraint('agent_run_created_by_fkey', 'agent_run', type_='foreignkey')
    op.drop_constraint('agent_run_approved_by_fkey', 'agent_run', type_='foreignkey')
    # NOTE: agent_run→operator FK deferred until after operator table is re-created
    op.drop_index('agent_run_created_by_idx', table_name='agent_run')
    op.drop_index('agent_run_business_id_idx', table_name='agent_run')
    op.drop_index('agent_run_business_id_created_at_idx', table_name='agent_run')
    op.create_index(op.f('agent_run_operator_id_idx'), 'agent_run', ['operator_id'], unique=False)
    op.create_index(op.f('agent_run_operator_id_created_at_idx'), 'agent_run', ['operator_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('agent_run', 'budget_cap',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('agent_run', 'risk_tolerance',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.35'))
    op.drop_column('agent_run', 'cancelled_at')
    op.drop_column('agent_run', 'cancelled_by')
    op.drop_column('agent_run', 'approved_at')
    op.drop_column('agent_run', 'approved_by')
    op.drop_column('agent_run', 'date_to')
    op.drop_column('agent_run', 'date_from')
    op.drop_column('agent_run', 'created_by')
    op.drop_column('agent_run', 'business_id')
    op.create_table('operator',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'analyst'::text"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role = ANY (ARRAY['analyst'::text, 'approver'::text, 'admin'::text])", name=op.f('operator_role_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('operator_pkey')),
    sa.UniqueConstraint('email', name=op.f('operator_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('external_id', name=op.f('operator_external_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'NGN'::bpchar"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transaction_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('merchant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('processor_response_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('processor_response_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('settlement_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_anomaly', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('anomaly_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("channel = ANY (ARRAY['CARD'::text, 'TRANSFER'::text, 'USSD'::text, 'QR'::text])", name=op.f('transaction_channel_check')),
    sa.CheckConstraint("status = ANY (ARRAY['SUCCESS'::text, 'PENDING'::text, 'FAILED'::text, 'REVERSED'::text])", name=op.f('transaction_status_check')),
    sa.CheckConstraint('amount >= 0::numeric', name=op.f('transaction_amount_check')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], name=op.f('transaction_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transaction_pkey')),
    sa.UniqueConstraint('run_id', 'transaction_reference', name=op.f('transaction_run_id_reference_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('transaction_timestamp_idx'), 'transaction', ['transaction_timestamp'], unique=False)
    op.create_index(op.f('transaction_run_id_status_idx'), 'transaction', ['run_id', 'status'], unique=False)
    op.create_index(op.f('transaction_run_id_idx'), 'transaction', ['run_id'], unique=False)
    op.create_table('plan_step',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("agent_type = ANY (ARRAY['planner'::text, 'reconciliation'::text, 'risk'::text, 'forecast'::text, 'execution'::text, 'audit'::text])", name=op.f('plan_step_agent_type_check')),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'skipped'::text])", name=op.f('plan_step_status_check')),
    sa.CheckConstraint('step_order >= 0', name=op.f('plan_step_step_order_check')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], name=op.f('plan_step_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_step_pkey')),
    sa.UniqueConstraint('run_id', 'step_order', name=op.f('plan_step_run_id_step_order_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('plan_step_run_id_idx'), 'plan_step', ['run_id'], unique=False)
    # Deferred FK creations — referenced tables (operator, plan_step) now exist
    op.create_foreign_key(op.f('payout_candidate_approved_by_fkey'), 'payout_candidate', 'operator', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('agent_run_operator_id_fkey'), 'agent_run', 'operator', ['operator_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('audit_log_step_id_fkey'), 'audit_log', 'plan_step', ['step_id'], ['id'], ondelete='SET NULL')
    op.drop_index('risk_score_feature_run_id_idx', table_name='risk_score_feature')
    op.drop_table('risk_score_feature')
    op.drop_index('payout_execution_run_id_idx', table_name='payout_execution')
    op.drop_index('payout_execution_interswitch_ref_idx', table_name='payout_execution', postgresql_where=sa.text('interswitch_reference IS NOT NULL'))
    op.drop_index('payout_execution_candidate_id_idx', table_name='payout_execution')
    op.drop_index('payout_execution_called_at_idx', table_name='payout_execution', postgresql_using='brin')
    op.drop_table('payout_execution')
    op.drop_index('customer_lookup_result_run_id_idx', table_name='customer_lookup_result')
    op.drop_index('customer_lookup_result_candidate_id_idx', table_name='customer_lookup_result')
    op.drop_table('customer_lookup_result')
    op.drop_index('approval_override_run_id_idx', table_name='approval_override')
    op.drop_index('approval_override_overridden_by_idx', table_name='approval_override')
    op.drop_index('approval_override_candidate_id_idx', table_name='approval_override')
    op.drop_table('approval_override')
    op.drop_index('transaction_anomaly_type_idx', table_name='transaction_anomaly')
    op.drop_index('transaction_anomaly_txn_id_idx', table_name='transaction_anomaly')
    op.drop_index('transaction_anomaly_run_id_idx', table_name='transaction_anomaly')
    op.drop_table('transaction_anomaly')
    op.drop_index('run_event_run_id_sequence_num_idx', table_name='run_event')
    op.drop_index('run_event_run_id_idx', table_name='run_event')
    op.drop_table('run_event')
    op.drop_index('api_call_log_step_id_idx', table_name='api_call_log')
    op.drop_index('api_call_log_run_id_idx', table_name='api_call_log')
    op.drop_index('api_call_log_called_at_idx', table_name='api_call_log', postgresql_using='brin')
    op.drop_table('api_call_log')
    op.drop_index('run_step_run_id_idx', table_name='run_step')
    op.drop_table('run_step')
    op.drop_index('reconciled_transaction_txn_timestamp_idx', table_name='reconciled_transaction')
    op.drop_index('reconciled_transaction_status_idx', table_name='reconciled_transaction')
    op.drop_index('reconciled_transaction_run_id_idx', table_name='reconciled_transaction')
    op.drop_index('reconciled_transaction_interswitch_ref_idx', table_name='reconciled_transaction')
    op.drop_index('reconciled_transaction_has_anomaly_idx', table_name='reconciled_transaction')
    op.drop_index('reconciled_transaction_business_id_idx', table_name='reconciled_transaction')
    op.drop_table('reconciled_transaction')
    op.drop_index('notification_outbox_user_id_idx', table_name='notification_outbox')
    op.drop_index('notification_outbox_unsent_idx', table_name='notification_outbox', postgresql_where=sa.text('is_sent = false'))
    op.drop_index('notification_outbox_scheduled_for_idx', table_name='notification_outbox')
    op.drop_index('notification_outbox_business_id_idx', table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_index('forecast_result_business_id_idx', table_name='forecast_result')
    op.drop_table('forecast_result')
    op.drop_index('invitation_expires_at_idx', table_name='invitation')
    op.drop_index('invitation_email_idx', table_name='invitation')
    op.drop_index('invitation_business_id_idx', table_name='invitation')
    op.drop_table('invitation')
    op.drop_index('business_member_user_id_idx', table_name='business_member')
    op.drop_index('business_member_business_id_idx', table_name='business_member')
    op.drop_table('business_member')
    op.drop_table('business_config')
    op.drop_table('user')
    op.drop_index('business_is_active_idx', table_name='business')
    op.drop_table('business')
    # ### end Alembic commands ###
