"""add_user_and_business_profile_columns

Revision ID: 6dcf0bf4dc3c
Revises: 00b9225e57e7
Create Date: 2026-03-11 15:49:08.821161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dcf0bf4dc3c'
down_revision: Union[str, Sequence[str], None] = '00b9225e57e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('rc_number', sa.String(length=50), nullable=True))
    op.add_column('business', sa.Column('tax_id', sa.String(length=50), nullable=True))
    op.add_column('business', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('business', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('business', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('business', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('business', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('job_title', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('timezone', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('external_provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'external_provider')
    op.drop_column('user', 'department')
    op.drop_column('user', 'timezone')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'job_title')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('business', 'phone')
    op.drop_column('business', 'website')
    op.drop_column('business', 'country')
    op.drop_column('business', 'state')
    op.drop_column('business', 'city')
    op.drop_column('business', 'tax_id')
    op.drop_column('business', 'rc_number')
    # ### end Alembic commands ###
