"""Add memory tables for Phase 7

Revision ID: 8558fff26e1d
Revises: a1b2c3d4e5f6
Create Date: 2026-03-21 08:23:51.895890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8558fff26e1d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary_reputation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('bank_code', sa.String(length=10), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=True),
    sa.Column('total_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('successful_payouts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_payouts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.0000'), nullable=False),
    sa.Column('total_amount_paid', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('average_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('last_outcome', sa.String(length=20), nullable=True),
    sa.Column('last_failure_reason', sa.String(length=100), nullable=True),
    sa.Column('last_payout_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reputation_score', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.5000'), nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reputation_score >= 0.0000 AND reputation_score <= 1.0000', name='beneficiary_reputation_score_check'),
    sa.CheckConstraint('success_rate >= 0.0000 AND success_rate <= 1.0000', name='beneficiary_reputation_success_rate_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number', 'bank_code', name='beneficiary_reputation_account_bank_uq')
    )
    op.create_index('beneficiary_reputation_reputation_idx', 'beneficiary_reputation', ['reputation_score'], unique=False)
    op.create_index('beneficiary_reputation_success_rate_idx', 'beneficiary_reputation', ['success_rate'], unique=False)
    op.create_table('business_pattern_profile',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('total_runs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_payouts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount_paid', sa.Numeric(precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('avg_candidates_per_run', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_amount_per_candidate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_std_dev', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_p25', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_p50', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_p75', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_p95', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('overall_success_rate', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.0000'), nullable=False),
    sa.Column('common_failure_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('recurring_beneficiary_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_success_rate >= 0.0000 AND overall_success_rate <= 1.0000', name='business_pattern_profile_success_rate_check'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_index('business_pattern_profile_business_id_idx', 'business_pattern_profile', ['business_id'], unique=False)
    op.create_table('run_outcome_memory',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('candidate_account_number', sa.String(length=20), nullable=False),
    sa.Column('candidate_bank_code', sa.String(length=10), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('risk_decision', sa.String(length=20), nullable=True),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('success', 'failed', 'rejected', 'pending', 'skipped')", name='run_outcome_memory_outcome_check'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0.0000 AND risk_score <= 1.0000)', name='run_outcome_memory_risk_score_check'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('run_outcome_memory_account_bank_idx', 'run_outcome_memory', ['candidate_account_number', 'candidate_bank_code'], unique=False)
    op.create_index('run_outcome_memory_business_id_idx', 'run_outcome_memory', ['business_id'], unique=False)
    op.create_index('run_outcome_memory_created_at_idx', 'run_outcome_memory', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('run_outcome_memory_outcome_idx', 'run_outcome_memory', ['outcome'], unique=False)
    op.create_index('run_outcome_memory_run_id_idx', 'run_outcome_memory', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('run_outcome_memory_run_id_idx', table_name='run_outcome_memory')
    op.drop_index('run_outcome_memory_outcome_idx', table_name='run_outcome_memory')
    op.drop_index('run_outcome_memory_created_at_idx', table_name='run_outcome_memory', postgresql_using='brin')
    op.drop_index('run_outcome_memory_business_id_idx', table_name='run_outcome_memory')
    op.drop_index('run_outcome_memory_account_bank_idx', table_name='run_outcome_memory')
    op.drop_table('run_outcome_memory')
    op.drop_index('business_pattern_profile_business_id_idx', table_name='business_pattern_profile')
    op.drop_table('business_pattern_profile')
    op.drop_index('beneficiary_reputation_success_rate_idx', table_name='beneficiary_reputation')
    op.drop_index('beneficiary_reputation_reputation_idx', table_name='beneficiary_reputation')
    op.drop_table('beneficiary_reputation')
    # ### end Alembic commands ###
