"""add_interswitch_audit_columns

Revision ID: 448015e66968
Revises: bba1244b626e
Create Date: 2026-02-28 23:54:09.127678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448015e66968'
down_revision: Union[str, Sequence[str], None] = 'bba1244b626e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_lookup_result', sa.Column('can_credit', sa.Boolean(), nullable=True))
    op.add_column('customer_lookup_result', sa.Column('transaction_reference', sa.String(length=255), nullable=True))
    op.add_column('institution', sa.Column('nip_code', sa.String(length=10), nullable=True))
    op.add_column('institution', sa.Column('cbn_code', sa.String(length=10), nullable=True))
    op.add_column('payout_candidate', sa.Column('transaction_reference', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payout_candidate', 'transaction_reference')
    op.drop_column('institution', 'cbn_code')
    op.drop_column('institution', 'nip_code')
    op.drop_column('customer_lookup_result', 'transaction_reference')
    op.drop_column('customer_lookup_result', 'can_credit')
    # ### end Alembic commands ###
