"""Static blocklist of disposable / temporary email providers.

Two-layer check at registration:
  1. This static set (fast, no network, covers the most common offenders).
  2. Optional external API (Abstract API) for extended coverage — see email_validator.py.

Keep sorted alphabetically to make PR diffs easy to review.
"""

BLOCKED_DOMAINS: frozenset[str] = frozenset(
    {
        "10minutemail.com",
        "10minutemail.net",
        "10minutemail.org",
        "10minemail.com",
        "20minutemail.com",
        "burnermail.io",
        "byom.de",
        "cock.li",
        "discard.email",
        "discardmail.com",
        "disposablemail.com",
        "disposableinbox.com",
        "dodgit.com",
        "drdrb.com",
        "dropmail.me",
        "emkei.cz",
        "fakeinbox.com",
        "fakemail.net",
        "filzmail.com",
        "fleckens.hu",
        "getnada.com",
        "getonemail.com",
        "guerrillamail.biz",
        "guerrillamail.com",
        "guerrillamail.de",
        "guerrillamail.info",
        "guerrillamail.net",
        "guerrillamail.org",
        "guerrillamailblock.com",
        "guestemail.net",
        "harakirimail.com",
        "inboxbear.com",
        "incognitomail.com",
        "jetable.fr.nf",
        "koszmail.pl",
        "kurzepost.de",
        "lol.ovh",
        "lookugly.com",
        "mailbucket.org",
        "mailchop.com",
        "mailexpire.com",
        "mailfence.com",
        "mailforspam.com",
        "mailguard.me",
        "mailimate.com",
        "mailinator.com",
        "mailme.ir",
        "mailme.lv",
        "mailmoat.com",
        "mailnesia.com",
        "mailnull.com",
        "mailscrap.com",
        "mailshell.com",
        "mailsiphon.com",
        "mailslapping.com",
        "mailslite.com",
        "mailtemp.info",
        "mailtothis.com",
        "mailtrash.net",
        "mailzilla.com",
        "maildrop.cc",
        "moakt.com",
        "mt2015.com",
        "mt2016.com",
        "mytrashmail.com",
        "nada.email",
        "nada.ltd",
        "nowmymail.com",
        "objectmail.com",
        "obobbo.com",
        "one-time.email",
        "owlpic.com",
        "pookmail.com",
        "proxymail.eu",
        "putthisinyourspamdatabase.com",
        "qq.com",  # commonly abused for throwaway accounts in Nigeria
        "rcpt.at",
        "recode.me",
        "recursor.net",
        "rtrtr.com",
        "sharklasers.com",
        "sharedmailbox.org",
        "shitmail.me",
        "spamail.de",
        "spam4.me",
        "spamfree24.org",
        "spamgourmet.com",
        "spamgourmet.net",
        "spamgourmet.org",
        "spamherelots.com",
        "spamhereplease.com",
        "spamhole.com",
        "spamify.com",
        "spamspot.com",
        "spamthis.co.uk",
        "spamtroll.net",
        "tafmail.com",
        "tempail.com",
        "tempe-mail.com",
        "tempemail.biz",
        "tempemail.co.za",
        "tempemail.com",
        "tempemail.net",
        "tempinbox.co.uk",
        "tempinbox.com",
        "tempmail.eu",
        "tempmail.io",
        "tempmail.net",
        "tempmail.ninja",
        "tempmail.org",
        "tempmail.us",
        "tempr.email",
        "thanksnospam.info",
        "throwam.com",
        "throwaway.email",
        "throwam.com",
        "tradermail.info",
        "trash-mail.at",
        "trash-mail.com",
        "trash-mail.io",
        "trash2009.com",
        "trashmail.at",
        "trashmail.com",
        "trashmail.io",
        "trashmail.me",
        "trashmail.net",
        "trashmail.org",
        "trashmail.xyz",
        "trillianpro.com",
        "twoweirdtricks.com",
        "uggsrock.com",
        "uroid.com",
        "veryrealemail.com",
        "wegwerf-email.de",
        "wegwerfadresse.de",
        "wetrainbayarea.org",
        "willhackforfood.biz",
        "xagloo.com",
        "xoxy.net",
        "yopmail.com",
        "yopmail.fr",
        "yopmail.net",
        "z1p.biz",
        "zippymail.info",
        "zoaxe.com",
        "zoemail.com",
        "zoemail.net",
    }
)


def is_blocked_domain(email: str) -> bool:
    """Return True if the email's domain is on the blocklist."""
    try:
        domain = email.strip().lower().split("@", 1)[1]
    except IndexError:
        return False
    return domain in BLOCKED_DOMAINS
